# HomeWork 1

## Q1 Pandas version

In [48]:
import pandas as pd
import numpy as np

In [8]:
pd.__version__

'3.0.6'

### Downloaded the .csv file

In [17]:
df=pd.read_csv('car_fuel_efficiency_2026.csv')

In [16]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q2. Records count

In [22]:
df.index

RangeIndex(start=0, stop=10000, step=1)

or

In [23]:
df.shape

(10000, 11)

Ans is 10000

## Q3. Fuel types

In [25]:
df.fuel_type.nunique()

3

In [29]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

## Q4. Missing values

In [30]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [31]:
(df.isnull().sum() > 0).sum()

np.int64(2)

## Q5. Max fuel efficiency

In [33]:
asia = df[df['origin'] == 'Asia']
asia['fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6 — Median value of horsepower

In [34]:
df['horsepower'].median()

np.float64(254.0)

In [35]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [36]:
mode = df['horsepower'].mode()[0]

In [37]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [38]:
df['horsepower'].median()

np.float64(252.0)

## Q7 Sum of weights

In [39]:
asia = df[df['origin'] == 'Asia']

In [40]:
X = asia[['vehicle_weight', 'model_year']]

In [41]:
X = X.head(7)

In [42]:
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [43]:
X = X.to_numpy()

In [44]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [46]:
XTX = X.T.dot(X)

In [50]:
XTX_inv = np.linalg.inv(XTX)

In [51]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [53]:
temp = XTX_inv.dot(X.T)
w = temp.dot(y)

In [54]:
w.sum()

np.float64(0.36919696904925486)